version: '3'

services:
  microservices-gateway:
    restart: always
    build:
      context: ./api-gateway
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    networks:
      - my-network
    volumes:
      - ./api-gateway:/apps/gateway
      - /apps/gateway/node_modules

  microservices-authentication:
    build:
      context: ./authentication
      dockerfile: Dockerfile.dev
    depends_on:
      - mongo_authentication
      - microservices-gateway
    ports:
      - "50051:50051"
    networks:
      - my-network
    volumes:
      - ./authentication:/apps/authentication
      - /apps/authentication/node_modules

  microservices-chat-messages:
    build:
      context: ./chat-messages
      dockerfile: Dockerfile.dev
    depends_on:
      - mongo_chat-messages
      - microservices-gateway
    ports:
      - "3001:3001"
    networks:
      - my-network
    volumes:
      - ./chat-messages:/apps/chat-messages
      - /apps/chat-messages/node_modules

  mongo_authentication:
    image: mongo
    command: mongod --quiet
    restart: always
    ports:
      - "27017:27017"
    networks:
      - my-network
    volumes:
      - mongo-authentication-data:/data/db

  mongo_chat-messages:
    image: mongo
    command: mongod --quiet
    restart: always
    ports:
      - "27018:27017"
    networks:
      - my-network
    volumes:
      - mongo-chat-messages-data:/data/db

networks:
  my-network:
    driver: bridge

volumes:
  mongo-authentication-data:
  mongo-chat-messages-data:
