apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.32.0 (765fde254)
  labels:
    io.kompose.service: microservices-chat-message
  name: microservices-chat-message
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: microservices-chat-message
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.32.0 (765fde254)
      labels:
        io.kompose.network/api-gateway-my-network: "true"
        io.kompose.service: microservices-chat-message
    spec:
      containers:
        - image: microservices-chat-message:latest
          name: microservices-chat-message
          imagePullPolicy: Never
          ports:
            - containerPort: 3001
              hostPort: 3001
              protocol: TCP
      restartPolicy: Always
