apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.32.0 (765fde254)
  labels:
    io.kompose.service: microservices-gateway
  name: microservices-gateway
spec:
  replicas: 2
  selector:
    matchLabels:
      io.kompose.service: microservices-gateway
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.32.0 (765fde254)
      labels:
        io.kompose.network/api-gateway-my-network: "true"
        io.kompose.service: microservices-gateway
    spec:
      containers:
        - image: microservices-gateway:latest
          name: microservices-gateway
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
              hostPort: 3000
              protocol: TCP
      restartPolicy: Always
