GET http://localhost:3000/example/hola
Cookie: jwt_access=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjYxMGRmYWMwNGE3NTdkOTA5ODQ4Nzg4IiwibWV0aG9kIjowLCJ0eXBlIjowLCJpYXQiOjE3MjY1MzUwNTMsImV4cCI6MTcyNjUzODY1M30.y87O2tv742LSKn_BXW84vUjnpE_bNc1yZluFvRdrAFE
Cookie: jwt_session=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjYxMGRmYWMwNGE3NTdkOTA5ODQ4Nzg4IiwibWV0aG9kIjowLCJ0eXBlIjoxLCJpYXQiOjE3MjY1MzUwNTMsImV4cCI6MTcyNjU1NjY1M30.PwtGe9AQYwSwO_IDQVtwosakGjrNzXXc_oaUzFKt74M
###

GET http://localhost:3000/auth/refreshToken
Cookie: jwt_session=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjYxMGRmYWMwNGE3NTdkOTA5ODQ4Nzg4IiwibWV0aG9kIjowLCJ0eXBlIjoxLCJpYXQiOjE3MjY1MzQ4NTcsImV4cCI6MTcyNjU1NjQ1N30.VoSB9Or_dVzcr6P_QuGmTrIw_HdHoZTj55xFneWE_G0
###

POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "dani@example.es",
    "password": "123"
}

###

POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "username": "dasniel1234542s2",
    "client_id": "6610df679aa69f94039714ef",
    "name": "Daniel Castillas",
    "email": "daniessl@example12352443.es",
    "password": "123"
}