FROM node:16-alpine
WORKDIR /apps/authentication

COPY package*.json ./
RUN npm install && npm cache clean --force

COPY . .

ENV DATABASE_HOST=mongo_authentication

EXPOSE ${PORT}

CMD ["npm", "run", "dev"]